# Generated by Django 3.2.4 on 2021-06-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
