# Generated by Django 3.2.4 on 2021-06-29 17:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('mgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
